name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nexus-battle-iv:latest .

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag nexus-battle-iv:latest camanrofo34/nexus-battle-iv:deploy
          docker push camanrofo34/nexus-battle-iv:deploy
